const INVALID_DATA_ERROR_CODE = 400;
const NO_DATA_ERROR_CODE = 404;
const DEFAULT_ERROR_CODE = 400;
const DUPLICATE_ERROR_CODE = 409;

module.exports = {INVALID_DATA_ERROR_CODE, NO_DATA_ERROR_CODE, DEFAULT_ERROR_CODE, DUPLICATE_ERROR_CODE};